name: bmrl
channels:
  - defaults
dependencies:
  - python==3.10
  - pyopengl
  - pytorch==2.0.1
  - matplotlib
  - pandas
  - numpy
  - tqdm
  - jupyter
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - gym==0.26.2
    - pygame==2.1.2
